version: "3"
services:
  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: postgres
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: "2gb"
  web: &app
    build: .
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      - /app/.git
    environment:
      HOME: /app
      RAILS_ENV: development
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000" #Rails
      - "3035:3035" #Webpacker
    tty: true

volumes:
  bundle:
    driver: local
  data:
    driver: local
